services:
  nats:
    image: nats:2.10
    ports:
      - "4222:4222"
      - "8222:8222"
  secured_nats:
    image: nats:2.10
    ports:
      - "4223:4222"
      - "8223:8222"
    #command: ["--tls", "--tlscert", "/tests/certs_insecure/server-cert.pem", "--tlskey", "/tests/certs_insecure/server-key.pem --tlshandshake"]
    command: ["--config", "/etc/nats/nats-server.conf"]
    volumes:
      - ./infra/nats/certs_insecure:/tests/certs_insecure
      - ./infra/nats/nats.conf:/etc/nats/nats-server.conf
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  app:
    image: alpine:latest
    container_name: app
    volumes:
      - ./cluster:/cluster
    command: /usr/local/bin/cluster
    entrypoint: sh -c "chmod +x /usr/local/bin/cluster && exec /usr/local/bin/cluster"
    healthcheck:
      test: "curl -f http://localhost:3000/health"
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M
    expose:
      - "8080"
    environment:
      DB_USER: user
      DB_PASSWORD: password
    depends_on:
      - db
      - nats
  nginx:
    image: nginx:latest
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "4000:4000"
